name: buslink
description: "Staff Transport Management System."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.6.0
  go_router: ^14.2.0
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  shared_preferences: ^2.2.3
  google_fonts: ^6.2.1
  geolocator: ^14.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
